// This file is auto-generated by build-sidecar.mjs at build time.
// During development, defaults to empty values; actual values are read from .env.
export const BUILD_CONSTANTS: Record<string, string> = {}
